PL/MIN-471 Basic operations
minterest-finance/frontend pull request #10
Opened 2021-07-12 07:13 UTC by l-polina

**Description:**

Implemented 4 basic operations in Prototype UI.

**Screenshots:**

![image](https://user-images.githubusercontent.com/61509290/125245923-d39dcb80-e2f9-11eb-9517-ad11405ff9e0.png)

2021-07-12 10:54 UTC, gavrilin-remote requested changes

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Forms/BorrowForm/index.tsx
> +							<div className='action-form-input-asset'>BTC</div>
Does this value should be hardcoded?

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Forms/BorrowForm/index.tsx
> +							<div className='action-form-conversion-value'>$0</div>
Does this value should be hardcoded?

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Forms/BorrowForm/index.tsx
> +							<div className='action-form-conversion-currency'>USD</div>
Does this value should be hardcoded?

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Forms/BorrowForm/validation.ts
> +		errors.underlyingAmount = 'Not enough wallet balance';
Let's translate this value

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Forms/Fields/CheckboxField/CheckboxField.tsx
> +	const {
The React recommended to destructure props right in arguments. Eg:
`CheckboxField({toggle, label, input: { value, onChange }}){...}`

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Forms/RedeemUnderlyingForm/validation.ts
> +		errors.underlyingAmount = 'Not enough wallet balance';
Let's translate this value

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Forms/RepayForm/validation.ts
> +		errors.underlyingAmount = 'Required';
Let's translate this value

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Forms/RepayForm/validation.ts
> +		errors.underlyingAmount = 'Not enough wallet balance';
Let's translate this value

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Markets/IsCollateral/index.tsx
> +					{isCollateralEnabled ? 'Enabled' : 'Disabled'}
Let's translate this value

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Markets/LendModal/index.tsx
> +		if (title === 'Lend') {
move 'Lend', 'Withdraw' etc in constants. You can use typescript enum for this purpose. 
Eg:
`enum ModalTypes{Lend='Lend', Withdraw='Withdraw', ...}`

and then use it in condition like `if(title === ModalTypes.Lend)`

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Markets/LendModal/index.tsx
>  export default function LendModal(props: LendModalProps) {
This modal seems to be very large, we should start thinking about refactoring. Pass tons of props - bad approach. We can connect each type of Modal content to redux, instead of passing a lot of props. Also, making conditional rendering based on `title` fields seems unsafe to me, what if title will change or we need translate it? 
Let's make a props `type` and make all conditions based on it. 
In `title` props you can pass i18n key.

2021-07-12 10:54 UTC, gavrilin-remote commented on src/components/Markets/LendModal/index.tsx
>  export default function LendModal(props: LendModalProps) {
Don't hesitate to ask a questions or advice.

2021-07-12 10:54 UTC, gavrilin-remote commented on src/containers/Markets/index.tsx
>  	} = props;
This component also need to be refactored. If we connect each Modal Type to redux, then we don't need to pass a lot of props.

2021-07-14 08:47 UTC, l-polina commented on src/components/Forms/BorrowForm/index.tsx
> +							<div className='action-form-input-asset'>BTC</div>
> Does this value should be hardcoded?

Passed an assetId instead of a hardcoded value.

2021-07-14 10:25 UTC, l-polina commented on src/components/Forms/BorrowForm/index.tsx
> +							<div className='action-form-conversion-value'>$0</div>
> Does this value should be hardcoded?

Added the conversion of the asset to dollars.

2021-07-14 10:33 UTC, l-polina commented on src/components/Forms/BorrowForm/index.tsx
> +							<div className='action-form-conversion-currency'>USD</div>
> Does this value should be hardcoded?

Added a constant instead of a hardcoded value.

2021-07-14 11:49 UTC, l-polina commented on src/components/Markets/IsCollateral/index.tsx
> +					{isCollateralEnabled ? 'Enabled' : 'Disabled'}
> Let's translate this value

translated this value

2021-07-14 14:06 UTC, l-polina commented on src/components/Forms/BorrowForm/validation.ts
> +		errors.underlyingAmount = 'Not enough wallet balance';
> Let's translate this value

translated this value

2021-07-14 14:06 UTC, l-polina commented on src/components/Forms/RedeemUnderlyingForm/validation.ts
> +		errors.underlyingAmount = 'Not enough wallet balance';
> Let's translate this value

translated this value

2021-07-14 14:06 UTC, l-polina commented on src/components/Forms/RepayForm/validation.ts
> +		errors.underlyingAmount = 'Required';
> Let's translate this value

translated this value

2021-07-14 14:35 UTC, l-polina commented on src/components/Forms/Fields/CheckboxField/CheckboxField.tsx
> +	const {
> The React recommended to destructure props right in arguments. Eg:
> `CheckboxField({toggle, label, input: { value, onChange }}){...}`

destructured the props right in the arguments

2021-07-15 06:53 UTC, l-polina commented on src/components/Markets/LendModal/index.tsx
> +		if (title === 'Lend') {
> use typescript enum

Used typescript enum

2021-07-15 06:54 UTC, l-polina commented on src/components/Markets/LendModal/index.tsx
>  export default function LendModal(props: LendModalProps) {
> This modal seems to be very large, we should start thinking about refactoring. Pass tons of props - bad approach. We can connect each type of Modal content to redux, instead of passing a lot of props. Also, making conditional rendering based on `title` fields seems unsafe to me, what if title will change or we need translate it?
> Let's make a props `type` and make all conditions based on it.
> In `title` props you can pass i18n key.

This refactoring will be implemented in another task.

2021-07-15 06:54 UTC, l-polina commented on src/containers/Markets/index.tsx
>  	} = props;
> This component also need to be refactored. If we connect each Modal Type to redux, then we don't need to pass a lot of props.

This refactoring will be implemented in another task.

2021-07-15 08:23 UTC, gavrilin-remote approved these changes

2021-07-15 10:09 UTC, merged