Min 521
minterest-finance/frontend pull request #19
Opened 2021-07-28 14:50 UTC by KirillBabuak

fixed update data after transaction:
![image](https://user-images.githubusercontent.com/26636078/127343439-b6b75d84-bd57-407f-b1bc-9222075573c2.png)
![image](https://user-images.githubusercontent.com/26636078/127343611-9e7221c7-3852-42f4-8f8b-61a982861aad.png)

additional fixed change button after success click:
![image](https://user-images.githubusercontent.com/26636078/127343804-06404273-6961-4cc9-9160-2720d82becc5.png)

2021-07-29 09:42 UTC, gavrilin-remote requested changes

2021-07-29 09:42 UTC, gavrilin-remote commented on src/util/formating.ts
> +	callback?: Function
I think passing the callback is not the proper solution for our purpose. 
1 - it hard to debug
2 - it hard to read
3 - it cause a code duplication.

I can suggest for you 2 solutions:
1. Dispatch your actions right after `signAndSend`, as I see this function return a promise, so any error cases will catched up by try/catch and you not need passing successfull callback into txCallback and make an unnecessary nesting of callbacks.
2. Crate a redux middleware to dispatch userUpdateInfoAction on specific actions. Eg. when is `DEPOSIT_UNDERLYING_REQUEST_SUCCESS` dispatched.

If you have any objections don't hesitate to argue with me. I'm not deeply immersed in this particular task, so can make a mistake

2021-07-30 06:19 UTC, l-polina commented on src/actions/userUpdates.ts
>  					// @ts-ignore
please, don't use @ts-ignore.

2021-07-30 06:33 UTC, l-polina approved these changes

2021-07-30 07:25 UTC, gavrilin-remote approved these changes

2021-07-30 07:27 UTC, merged