[MIN-535] reset form after change collateral
minterest-finance/frontend pull request #20
Opened 2021-07-29 19:33 UTC by KirillBabuak

Reset form after click on collateral
blob:https://minterestfinance.atlassian.net/d5a13c75-9bb3-4b21-be07-3f4f6d5f718f

2021-07-29 19:34 UTC, KirillBabuak commented
Merge after branch MIN-521

2021-08-09 07:26 UTC, gavrilin-remote requested changes

2021-08-09 07:26 UTC, gavrilin-remote commented on src/components/Markets/LendModal/index.tsx
> +		dispatch(initialize(formType, {}));
Why do you use initialize with empty object instead of `reset`? https://redux-form.com/6.0.0-alpha.4/docs/api/actioncreators.md/

2021-08-09 07:31 UTC, KirillBabuak commented on src/components/Markets/LendModal/index.tsx
> +		dispatch(initialize(formType, {}));
i use initialize, because reset function set only initial values, but does not reset the field state (the field has status that it has changed). I found only this case how reset field status

2021-08-09 08:13 UTC, gavrilin-remote commented on src/components/Markets/LendModal/index.tsx
> +		dispatch(initialize(formType, {}));
Ok, can you please add comment or todo? It's looks like a workaround, but not critical, we can return to it in future.

2021-08-09 08:16 UTC, KirillBabuak commented on src/components/Markets/LendModal/index.tsx
> +		dispatch(initialize(formType, {}));
where do I must add comment or todo?

2021-08-09 08:21 UTC, gavrilin-remote commented on src/components/Markets/LendModal/index.tsx
> +		dispatch(initialize(formType, {}));
In the code, above `dispatch(initialize(formType, {}));`

2021-08-09 10:19 UTC, l-polina commented on src/components/Markets/LendModal/index.tsx
> +		dispatch(initialize(formType, {}));
> In the code, above `dispatch(initialize(formType, {}));`

Added comment

2021-08-09 10:20 UTC, l-polina approved these changes

2021-08-09 10:26 UTC, gavrilin-remote approved these changes

2021-08-09 10:26 UTC, merged