MK/MIN-319
minterest-finance/frontend pull request #6
Opened 2021-06-10 14:25 UTC by l-polina

**Description:**

Implemented connection to the polkadot.js extension. Received and displayed data: Lend Balance, Borrow balance, Total Lent, Total Borrow and Collateral Ratio.

**Screenshots:**

![image](https://user-images.githubusercontent.com/61509290/121540614-4c65eb00-ca0f-11eb-9356-194498e427de.png)
![image](https://user-images.githubusercontent.com/61509290/121540684-5be53400-ca0f-11eb-8a8f-7d412ad981a2.png)
![image](https://user-images.githubusercontent.com/61509290/121540936-8931e200-ca0f-11eb-9d93-991a1ef9c9c4.png)

2021-06-11 07:41 UTC, gavrilin-remote requested changes

2021-06-11 07:41 UTC, gavrilin-remote commented on src/components/Markets/BorrowMarkets/index.tsx
>  	const assetsList = ['BTC', 'ETH', 'DOT', 'KSM'];
move constant out of Functional Component

2021-06-11 07:41 UTC, gavrilin-remote commented on src/components/Markets/BorrowMarkets/index.tsx
> +
memoize values totalBorrowPerAsset, currentPricePerAsset and totalBorrowInUSD with useMemo hook.

2021-06-11 07:41 UTC, gavrilin-remote commented on src/components/Markets/LendMarkets/index.tsx
>  	const assetsList = ['BTC', 'ETH', 'DOT', 'KSM'];
move constant out of Functional Component

2021-06-11 07:41 UTC, gavrilin-remote commented on src/components/Markets/LendMarkets/index.tsx
> +
memoize values totalLentPerAsset, currentPricePerAsset and totalLentInUSD with useMemo hook.

2021-06-11 07:41 UTC, gavrilin-remote commented on src/components/Markets/MarketUserBalance/index.tsx
> +	const collateralRatio =
memoize this function with useMemo

2021-06-11 07:41 UTC, gavrilin-remote commented on src/components/Widgets/CollateralRatioWidget/index.tsx
> +	const coef = 135 / 50;
move constants out of Functional Component

2021-06-12 11:14 UTC, l-polina commented on src/components/Markets/BorrowMarkets/index.tsx
>  	const assetsList = ['BTC', 'ETH', 'DOT', 'KSM'];
> move constant out of Functional Component
The asset list is sourced from BE.

2021-06-12 11:14 UTC, l-polina commented on src/components/Markets/LendMarkets/index.tsx
>  	const assetsList = ['BTC', 'ETH', 'DOT', 'KSM'];
> move constant out of Functional Component

The asset list is sourced from BE.

2021-06-14 13:14 UTC, l-polina commented on src/components/Markets/LendMarkets/index.tsx
> +
> memoize values totalLentPerAsset, currentPricePerAsset and totalLentInUSD with useMemo hook
memoized values ​​totalLentPerAsset, currentPricePerAsset and totalLentInUSD with useMemo hook

2021-06-14 13:15 UTC, l-polina commented on src/components/Markets/BorrowMarkets/index.tsx
> +
> memoize values totalBorrowPerAsset, currentPricePerAsset and totalBorrowInUSD with useMemo hook.

memoized values totalBorrowPerAsset, currentPricePerAsset and totalBorrowInUSD with useMemo hook

2021-06-14 14:03 UTC, l-polina commented on src/components/Markets/MarketUserBalance/index.tsx
> +	const collateralRatio =
> memoize this function with useMemo

memoized this function with useMemo

2021-06-14 14:11 UTC, l-polina commented on src/components/Widgets/CollateralRatioWidget/index.tsx
> +	const coef = 135 / 50;
> move constants out of Functional Component

moved constant

2021-06-14 14:27 UTC, gavrilin-remote approved these changes

2021-06-14 14:35 UTC, merged